### ISSUE TITLE
Some thoughts on architecture

### ISSUE THREAD

**Issue by MOZGIII** [kenn/dumper#12]
Context: I received an email asking what I think about dumper.io. Haven't used it, didn't read the code (yet).

After a quick look, it seems the database backup procedures are supposed to run from the same process that serves the HTTP requests.
I think this a bad choice to carry on such operations, mainly because it breaks separation of concerns for processes. This is important ruby web server handles just web requests, and doesn't try doing anything else, especially tasks with different lifecycle models. Not a big deal for small projects, but after a certail system size and load this becomes important.

There are a lot of potential issues with threading (if you use standard ruby implementation, and even with jruby). Basicly, it depends on the workload types and the load that each server has to handle, but given the interpreter thread would block on system calls and database drivers ruby are typically implemented using blocking API - doing database activity in the background may cause unwanted behavior and a decrease in service quality during the backup.
UPD: ok, scratch this part, I've checked out the readme and the execution model is alright (won't be causing the issues I'm describing).

The other issue is the database backup process should really be managed separately from any other job types: having a separate small process would be a better solution in my opinion. It has a benefit of having the ability to spawn in wherever needed - given I typically deploy separate nodes for web servers, background jobs workers and other stuff. Having a separate web server nodes makes the system load on the nodes more predictable and easier to manage. For example, memory consumption is very different on web and background job worker nodes in a typical deployment. Having said that, it seems to be a much better idea to have a separate node for such kind of process. We're talikng about database backups - it doesn't need to scale together with web servers (hopefully).

That's my thoughts.

### Some more thoughs on the general approach to database backups

Postgres is my most used database, so I'll be talking about it. Probably this can be applied to other databases.

In general, for postgres backups today I'd use some solution that stores WALs and periodically does the full database snapshots. This is better than just a dump, because with such approach the backup sizes are much smaller, and there's no load to the database server (except for the file copying) or table locking - so the backup can be done online. A small bonus is that one could restore the database to a specific point in time, not just to the predefined snapshot, as long as that point in time is covered my WALs you have.
An example of this technique can be seen in the snapshotting implemnetation of AWS RDS for Postgres.

This, of course, is not directly relevant to the `dumper` because it's a different approach to the same problem. But I just wanted to share my thoughs on this topic too. I'd still find usecases for something similar to `dumper`, but probably for managing the development environment.

**Comment by kenn** [comment]
Hey @MOZGIII, thanks for your thoughts.

Dumper agent runs as a thread, just like (everyone's favorite) [New Relic](https://newrelic.com/) does, and its sole purpose is mostly to sleep and wakes up every 1-10 minutes to check if there's a job, and when there's a job, we `fork(2)` a child process that lives independent from the web app processes, and then it `fork-exec` a command line tool such as `pg_dump`. We even use `posix_spawn(3)` to ensure O(1) fast forking from a large Rails process.

And if you use forking web servers such as Unicorn, Passenger or Puma, the agent only runs inside the singleton, master process because the only current thread is inherited to a child process on Linux and worker processes won't have the agent thread. Therefore, by design, only one agent runs per server (and it's also configurable - you can specify which process/server you want to run the agent thread on). The overhead of all this is negligible, and in fact, no customers reported increased server resource usage so far.

Obviously, Dumper is not intended to be used by Facebook or Google, but for small- to mid-sized projects that includes up to 10-20 servers, the architecture makes sense I believe.

As to postgres using WAL (in case of MySQL, binlog), I agree that incremental backups are desirable to minimize the load to the database. But also keep in mind that when restoring, you need to start roll-forward from the last dump, which can be very far away, and so many files can be involved that is prone to trigger the secondary error during the manual operation. For that reason, most DB admins take a logical dump every once in a while anyway. But thank you for pointing that out, WAL/binlog support is actually on the upcoming feature list.

Thanks for your feedback! 👍

**Comment by MOZGIII** [comment]
Don't know about backups, but I'd really look forward to some semi-hosted (like dumper) online migration implementations.

**Comment by kenn** [comment]
What do you mean by migration?

**Comment by MOZGIII** [comment]
DB schema and data updates (stuff you usually run along with the application code updates).

**Comment by MOZGIII** [comment]
For example, this is an opensource online migration tool for MySQL (why do people even use it now?) from GitHub: https://github.com/github/gh-ost

**Comment by kenn** [comment]
Ah, ok. Online migration tools are critical if you have a large table because basically it makes the table read-only during `ALTER TABLE`, which is often unacceptable. I like Github's implementation because it's trigger-less. In any case, it's an advanced topic for relatively large scale projects. Maybe replica as a service can be a possible solution?

**Comment by MOZGIII** [comment]
Maybe, I don't really know. I've implemeted this paradigm couple times. In general you'd need a smart database balancer (like pg_bouncer, but hooked into some state manager), and the logic to apply migrations. Databases usually go blue-green, so users would probably provide their own replicas.

The thing is, there are a lot of different usecases, however there's still some common logic around the online migration process that can be automated. Like switching the databases on balancer and rolling app updates. Probably this would work best if integrated with kubernetes or sth like that.

**Comment by MOZGIII** [comment]
And the reason I want a semi-hosted service (or a tool) for that is because it's one of those things that you don't want to invest into as a typical online business owner (unless you really have resource to spare), but as an engineer it would benefit you a lot.

**Comment by kenn** [comment]
Yeah, I hear you. It's a PITA for sure, and kubernetes / blue-green mitigated some, but so far as I can see, there's no single best practice. That makes it really hard to generalize as a product. Anyway, thanks for the input - it's a good discussion. 😄
